using System;
namespace eCommerce.Fonts
{
	// Generated by IconFont2Code: https://andreinitescu.github.io/IconFont2Code
	static class FontAwesome5Solid
	{
		public const string AngleLeft = "\uf104";
	}
}
