using System;
namespace eCommerce.Fonts
{
	// Generated by IconFont2Code: https://andreinitescu.github.io/IconFont2Code
	public static class IcoMoonFree
	{
		public const string ArrowLeft = "\uea38";
		public const string Heart = "\ue9da";
		public const string AngleLeft = "\uea40";
		public const string Menu = "\uea78";
	}
}
